# Generated by Django 3.1.3 on 2021-04-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typecontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
